### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by tianitol** [tianitol/DEV002-md-links#10]
General

- [ ] Puede instalarse via npm install --global <github-user>/md-links

README.md

- [ ]     Un board con el backlog para la implementación de la librería.
- [ ]     Documentación técnica de la librería.
- [ ]     Guía de uso e instalación de la librería

API mdLinks(path, opts)

- [x]     El módulo exporta una función con la interfaz (API) esperada.
- [x]     Implementa soporte para archivo individual
- [x]     Implementa soporte para directorios
- [x]     Implementa options.validate

CLI

- [x] Expone ejecutable md-links en el path (configurado en package.json)
- [x]     Se ejecuta sin errores / output esperado
- [x]     Implementa --validate
- [x]     Implementa --stats

Pruebas / tests

- [x] Pruebas unitarias cubren un mínimo del 70% de statements, functions, lines, y branches.
- [x]     Pasa tests (y linters) (npm test).
